spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 806186987@qq.com
    password: ooqekvuafiofbdic
    port: 587
    properties:
      mail:
        stmp:
          ssl:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
  datasource:
    dynamic:
      primary: read-mysql1
      strict: false
      datasource:
        read-mysql1:
          type: com.zaxxer.hikari.HikariDataSource
          dirver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-bp1f60sm3gkeh40uhqo.mysql.rds.aliyuncs.com:3306/order?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
          username: root
          password: gwq_806186987
        write-mysql:
          type: com.zaxxer.hikari.HikariDataSource
          dirver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/order?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
          username: root
          password: gwq806186987
        read-mysql2:
          type: com.zaxxer.hikari.HikariDataSource
          dirver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-bp1f60sm3gkeh40uhqo.mysql.rds.aliyuncs.com:3306/order2?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
          username: root
          password: gwq_806186987



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    设置mybatis-plus的全剧配置
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
